#pragma once

void default_constants();
void localization_telemetry_update();
void localization_telemetry_reset();
bool localization_set_runtime_start_pose(double x_in, double y_in, double heading_deg);
void localization_get_runtime_start_pose(double& x_in, double& y_in, double& heading_deg);
void localization_slow_rotation_calibration();
void localization_slow_forward_calibration();
void localization_fused_rotation_health_test();
void localization_fused_relative_motion_test();
void localization_fused_boomerang_test();
void localization_navigation_qualification_route();
void localization_navigation_api_boundary_test();
void localization_navigation_dropout_abort_test();
void localization_navigation_obstacle_abort_test();
void localization_navigation_straight_qualification();
void localization_navigation_bidirectional_qualification();
void localization_navigation_turn_qualification();
void localization_navigation_turn_recovery_qualification();
void localization_navigation_mirrored_curve_qualification();
void localization_navigation_obstacle_approach_qualification();
void localization_navigation_reverse_recovery();
void localization_slider_slow_picture_test();
void localization_all_mechanisms_test();
void localization_clamp_picture_test();
void localization_toggle_goal_example_auton();
void localization_toggle_goal_continue_auton();
bool localization_toggle_far_goal_hotkey_auton();
bool localization_pure_pursuit_endpoint_test();
bool localization_far_goal_trial_recover_to_start();
void localization_navigation_return_route();
void localization_drive_response_test();
void simple_goal_avoidance_auton();
void fusion_test_auton();
void gps_obstacle_aware_route_test();
